### ISSUE TITLE
Add SQLite backing for user service

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#1]
As a project maintainer, I want a dynamic user table so that I can add and remove users at will. There are currently None and FileMethod backings for the user service, this task should add a third that communicates with a sqlite database.

**Comment by jmandel** [comment]
Perfect, thanks! Definitely had real db in mind when I inserted this "method" abstraction -- but if you find the abstraction needs tweaking as you go  (e.g. as in #3),   go right ahead!
