### ISSUE TITLE
Add missing resource types to security whitelist

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#10]
There are two Resource types (DocumentReference and MedicationAdministration) referenced on http://syncfor.science/api-calls/ that are not present in the security resource whitelist.

**Comment by jmandel** [comment]
Ah, that's what "blocked" means :-) Good catch.

**Comment by jmandel** [comment]
So, the cross-repo references work, but you can't actually _close_ an issue. Manual step...

**Comment by jmandel** [comment]
Hmm, https://github.com/blog/1439-closing-issues-across-repositories suggests it should work. Let me check permissions.
