### ISSUE TITLE
Update our SNOMED to US Edition

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#111]
TODO: Ensure that US Edition is a superset of international edition.

https://github.com/sync-for-science/test-suite/blob/510a320f4e240e573b5d6e43e41f7bf2765caa92/data/build_bf.py#L30 should download the US Edition

**Comment by erikwiffin** [comment]
From: https://www.nlm.nih.gov/healthit/snomedct/us_edition.html
> In addition to 490 new concepts specific to the US, the March 2017 SNOMED CT US Edition also contains all of the content from the January 2017 International Release of SNOMED CT.
