### ISSUE TITLE
Still embedding failure content as raw HTML

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#114]
![image](https://user-images.githubusercontent.com/313089/28691284-59a618f6-72ea-11e7-8ef5-b4d74788a721.png)

is an example of a failure — we're xss'ing oureslves by embedding these responses in our page without encoding :-)

**Comment by erikwiffin** [comment]
This is actually fixed in the test suite, but the reference stack needs to be updated. Will hold off on this until all the test suite fixes are ready to go live so that we can grab them all at once.

**Comment by mtmcduffie** [comment]
@jmandel - Do you remember how to replicate this? If it's not happening on the tests.demo server I think we can can this one.

**Comment by jmandel** [comment]
We didn't have a test in place for this -- it happened when conveying (passing through) the text of errors from a source portal.
