### ISSUE TITLE
"See failure details" opens and closes

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#115]
I'm currently seeing the failure details "new tab" and then instantaneously close when I try this in the local test suite (in Chrome, but not in Firefox). Have you seen this before @erikwiffin? (I can work around by "copy link location" and pasting into a new tab.)

**Comment by jmandel** [comment]
I can't reproduce this anywhere but one machine.

**Comment by erikwiffin** [comment]
I've never seen this either. Could possibly be a bug related to the latin/utf8 thing you fixed yesterday?
