### ISSUE TITLE
Text encoding error crashes test suite

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#116]
Running tests against Johnson in pilot prep, the UI hangs at the "EHR evaluates authorization request" step and the console shows:

```
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

... have you seen this before @erikwiffin? I'm guessing we have an issue with our extra-tricky state characters.

**Comment by jmandel** [comment]
Yeah, this issue happens when we try to create the "open error report in new tab" links (encoding our data URLs). It only crops up on servers that fail this test, because on success, we don't try to encode these special characters in an error report...

**Comment by jmandel** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_1_–_escaping_the_string_before_encoding_it has info on the problem + solutions.

**Comment by jmandel** [comment]
For us, [Solution (2)](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_2_–_rewrite_the_DOMs_atob()_and_btoa()_using_JavaScript's_TypedArrays_and_UTF-8) looks like it might apply.

**Comment by erikwiffin** [comment]
You fixed this with https://github.com/sync-for-science/test-suite/pull/111, right?

**Comment by jmandel** [comment]
Almost. sync-for-science/test-suite#11 didn't actually `npm build`. (We might want to remove the built code from git and make npm build a part of the docker build process so this doesn't happen...)

**Comment by erikwiffin** [comment]
Gotcha. I can push up a build commit.

I'd prefer to avoid having npm build be a part of the docker build, since that would require the container to have node and npm available, as well as download all the required packages (this is incredibly irritating when python requirements change, because of sequential docker builds, you end up also waiting for an entire npm re-download). I think a git commit/push hook might be a better way to resolve this.

**Comment by erikwiffin** [comment]
Pushed directly to master https://github.com/sync-for-science/test-suite/commit/730735e2c39eebf14ada6f4704f1330fb8154565, we can close this now?

**Comment by jmandel** [comment]
OK by me! Thanks.

**Comment by jmandel** [comment]
Good as done!

**Comment by erikwiffin** [comment]
There isn't an obvious way to commit a git hook with the repo, but you're welcome to use this https://gist.github.com/erikwiffin/a7e76373c1cf21fb9dc80a2655e0bccc

It'll run `npm run build` on `git push`, and if that changes anything, it'll cancel your push with a reminder to commit the new bundle files. You should be able to bypass it with `git push --no-verify`, although I have not "verified" that.
