### ISSUE TITLE
Review argonaut profile valueset URIs

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#119]
For example on `AllergyIntolerance.status`:

Trimmed payload below exhibiting the issue...

```
Assertion Failed: active is not found in http://hl7.org/fhir/allergy-intolerance-status.
{
  "reaction": [
    {
      "manifestation": [
        {
          "text": "unknown"
        }
      ],
      "description": "Anaphylaxis"
    }
  ],
  "resourceType": "AllergyIntolerance",
  "category": "medication",
  "status": "active"
}
```

**Comment by jmandel** [comment]
A good approach would be:

1. Make sure our vocab file builder (https://github.com/sync-for-science/test-suite/tree/master/data) can download as many vocabs as possible automatically (but leave SNOMED, LOINC for developers to sign in)

2. Move the `.bf` (bloom filter file with our compiled vocab list) out of git and into... somewhere. Maybe a github "release" file, or and S3 bucket, or whatever.

**Comment by erikwiffin** [comment]
If you're in here making changes anyways, a personal "nice-to-have" would be to move the invocation of `build_bf.py` into a flask command line script http://flask.pocoo.org/docs/0.12/cli/

**Comment by mtmcduffie** [comment]
Also to note, the Assertion we are failing on should be the blanket for covering the missing data on our end.

**Comment by mtmcduffie** [comment]
Updating with some recent discussion - some of these are validated by the virtue of being good FHIR or not as decided by the FHIR server. The extra validation step of checking the codes in our Bloom filter fails as those valuesets are not in there.

**Comment by mtmcduffie** [comment]
I created (https://github.com/sync-for-science/tracking/issues/161) and (https://github.com/sync-for-science/tracking/issues/162) to address issues around updating bloom filter and validation. Okay to close this particular ticket @jmandel ?

**Comment by jmandel** [comment]
Okay by me;
