### ISSUE TITLE
In api-call docs, show data via links (or ajax) rather than hard-coding?

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#12]
As we update our sample data over the course of the project, it would be good not to have to keep the /api-calls page manually updated along the way. Maybe we could just:
1. Add an open FHIR proxy to our reference stack (next to the OAuth-protected one)
2. Add a FHIR client to our API-calls page, so that queries are executed dynamically

Thoughts @erikwiffin  ?

**Comment by erikwiffin** [comment]
I think that's a really good idea. We could probably get rid my show/hide hack as well and just fire the request on user action.

**Comment by jmandel** [comment]
This is fixed by https://github.com/sync-for-science/sync-for-science.github.io/pull/5
