### ISSUE TITLE
Updates to demo env have broken test suite config

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#122]
Visiting https://tests.demo.syncfor.science and running tests against SMART, Epic, or Allscripts, for example, show issues:

* Authorization error with trouble playing the sign-in/approval steps
* Screenshot links are pointing to `localhost` instead of `demo.syncfor.science` (e.g. "For more information, see:
http://localhost:9003/static/screenshots/f9275fd8-f1f0-4700-814b-1e32d5bb5a17.png")

Maybe there was an issue in copying the vendor-specific configs to the /configuration dir of the host machine?

**Comment by mtmcduffie** [comment]
Ah, I made the mistake of assuming the source on the server was up to date, it wasn't. Were some of the tests not running before (Namely - drchrono, athenahealth, McKesson, Other) ?

**Comment by jmandel** [comment]
Ah, that'd do the trick! And yes: the four sites are you listed are not
expected to run successfully :)

On Oct 4, 2017 21:19, "Michael Tommie McDuffie" <notifications@github.com>
wrote:

Ah, I made the mistake of assuming the source on the server was up to date,
it wasn't. Were some of the tests not running before (Namely - drchrono,
athenahealth, McKesson, Other) ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sync-for-science/tracking/issues/122#issuecomment-334333187>,
or mute the thread
