### ISSUE TITLE
Testing dev.bluebutton.cms.fhirservice.net

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#125]
Thanks to @mtmcduffie we now have a public Test Suite that can run tests against the CMS dev portal at https://dev.bluebutton.cms.fhirservice.net !

### TODOS

- [x] #126
- [x] #127
- [x] #129

## To try it:

1. Navigate to STU3 Test Suite at https://tests-stu3.demo.syncfor.science
2. Choose "CMS"
3. Click "Run Tests"

We've got lots of TODOs which we can link to this issue. But we have a starting point :-)

**Comment by jmandel** [comment]
@aviars @ekivemark FYI. We've got a bit of cleanup before this is really ready, but feel free to click around and try this out :-)

**Comment by aviars** [comment]
How exactly do I exercise the Sync4Science test suite @jmandel?

**Comment by jmandel** [comment]
Visit https://tests.demo.syncfor.science, choose "CMS", and click "Run Tests". This is very much a work in progress, but we'd love feedback!

Cc @mtmcduffie

**Comment by jmandel** [comment]
(In particular, we know that "Implements all the S4S requirements" is wrong, and we're introducing a notion of "use cases" so we can assess whether a given server meets S4S requirements *for its use case* -- e.g. financial data.)
