### ISSUE TITLE
GET URL for Patient uses the wrong path in STU3 Test Suite

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#126]
Running the STU3 Test Suite shows this API call for `Patient`

![image](https://user-images.githubusercontent.com/313089/31966655-59d4629e-b8d9-11e7-8c72-f03bc885c972.png)

In other words, a GET to `https://dev.bluebutton.cms.fhirservice.net/protected/bluebutton/fhir/v1/metadataPatient/Tbt3KuCY0B5PSrJvCu2j-PlK.aiHsu2xUjUM8bWpetXoB`. Should presumably be `https://dev.bluebutton.cms.fhirservice.net/protected/bluebutton/fhir/v1/Patient/Tbt3KuCY0B5PSrJvCu2j-PlK.aiHsu2xUjUM8bWpetXoB`

**Comment by mtmcduffie** [comment]
Fixed here - https://github.com/sync-for-science/reference-stack-docker/commit/631b937c572762fc1d257074450f73936705801b
