### ISSUE TITLE
Differentiate on syncfor.science/api-calls page the EHR Portal vs Claims, Imaging, etc portals

### ISSUE THREAD

**Issue by mtmcduffie** [sync-for-science/tracking#136]

**Comment by jmandel** [comment]
I added https://github.com/sync-for-science/sync-for-science.github.io/commit/516da7b3cca8cd16c26cac5fc4edab8c614b8841#diff-d432732a7807a086b93dba376e727def -- see if this helps?

**Comment by mtmcduffie** [comment]
Thanks! Sorry if this issue spurred action, I was moving it out of to do because I knew you had started it. It looks good.
