### ISSUE TITLE
Stub out patient flow

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#14]
Convert all the mockups from http://joshuamandel.com/s4s-ux-mockup into actual endpoints.

**Comment by erikwiffin** [comment]
Completed with https://github.com/sync-for-science/reference-research-app/commit/16dd936eecd077df037f1332b957d740f6194395

**Comment by jmandel** [comment]
Nice! As we move forward on this I'll encourage you to take a stronger backend/frontend separation here where the Python side provides an API to a static web frontend (it's my bias for design, and you can push back of course if you find this distasteful).
