### ISSUE TITLE
Error while running token introspector project.

### ISSUE THREAD

**Issue by gadregit** [sync-for-science/tracking#151]
The error says :
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

What should be the output of this project, when we perform flask run.

Thanks for the help.

**Comment by mtmcduffie** [comment]
@gadregit - Can you provide a little more information, perhaps a log from your console of the commands you are running and the message you are getting?

**Comment by mtmcduffie** [comment]
Closing for now, if @gadregit comes back with more info will evaluate.
