### ISSUE TITLE
Cron to periodically scrape new resources

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#22]
As a research app, I want to routinely query all the resources that I have access to.

Figuring this out is a bit trickier. Spreading out all the requests that we need to make over a reasonable window is not an obviously straightforward process. Something like this is probably a good start http://blog.databigbang.com/category/web-crawling/.

**Comment by erikwiffin** [comment]
There will probably only be a couple "participants" (10ish?) so this may not be necessary.

Also, how will we map FHIR Patients to "participants". Maybe we only have one FHIR Patient for everyone.

**Comment by jmandel** [comment]
I thank this is slightly backwards: we might have just one "participant" (i.e. Just one "user" in our PMI app) but that user would connect to 8 different EHRs (ours plus seven vendors') meaning 8 different FHIR Patient records would exist.

**Comment by erikwiffin** [comment]
This looks fixed.
