### ISSUE TITLE
Re-design "connected" page

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#27]
- Don't show multiple authorizations for the same provider.
- Group resources by provider.
- Have some mechanism for inspecting the shared resources.
- Include Patient resource in sync'd resources list.

**Comment by erikwiffin** [comment]
- Have a link into it from the home page.

**Comment by jmandel** [comment]
Fixed in https://github.com/sync-for-science/reference-research-app/pull/12
