### ISSUE TITLE
Incorporate conformance statement into tests

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#31]
Write a test for conformance statements to verify that they contain all of the required S4S resources. Then, write a "given" clause for individual resource tests that will skip them if they are not present in the conformance statement.

This will save time in testing resources that vendors do not currently support, and solves the issue of requiring _at least_ one of the Medication resources.

**Comment by jmandel** [comment]
- Before running any tests: download the servers `/metadata`. Save this `Conformance` statement.
- Add tests to ensurethat
  -  >=1 of `Medication`{`Statement`, `Order`, `Dispense`, `Administration`} is supported
  - all other S4S resource (including AllergyIntolerance) are supported
- Before running each test, check saved Conformance, and skip this test if this resource is not supported

**Comment by erikwiffin** [comment]
Fixed in https://github.com/sync-for-science/test-suite/pull/19.
