### ISSUE TITLE
bitbucket failing for phantomjs

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#35]
https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs suggests we should be downloading from github (and, well, bitbucket is failing intermittently). @erikwiffin can you remind me why you switched from GH -> bitbucket in https://github.com/sync-for-science/reference-stack-docker/commit/4bfb1d7c8894456ac07b12ee3663b0bcdb8e8dac#diff-ca1cdbd05fcfab95e1c3e1f4fb6d9345L17 ?

**Comment by erikwiffin** [comment]
I got the bitbucket url from the phantomjs website: http://phantomjs.org/download.html.
I switched because curl wasn't properly downloading the github url, but then I also switched to wget, so maybe the github url would work again. Has the bitbucket URL been giving you trouble?

**Comment by jmandel** [comment]
Yes, failing intermittently :) you can see evidence in docker hub logs.
