### ISSUE TITLE
Add logging functionality

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#4]
As a project maintainer, I want to be able to track what requests are being made against the gateway, so that I can tell consumers if they're doing it right.

We'll need to add another service type "logging" to the existing services, and provide None and DB implementations.

Not sure if it makes more sense to trigger the log from `smart/reverse_proxy.js` or `services/security.js`. Security.js is going to have greater insight into what’s being requested anyways, so I’m inclined to go with that.

**Comment by jmandel** [comment]
The use case for this logging service is  for patients (end users)  too: we want to show them who has been accessing their data, by displaying this in the portal.

**Comment by jmandel** [comment]
And yes, security.js seems like a good hook point. I would say give it a shot and see if you run into any trouble.

**Comment by jmandel** [comment]
GET /who-can-access-my-stuff

--> {
 derived from sqllite table of access tokens  
}

**Comment by erikwiffin** [comment]
This exists in a pretty rough form as /api/me in the new auth_proxy.
