### ISSUE TITLE
Log to ElasticSearch with parsed JSON bodies

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#45]
We should speculatively log the `.json()` value of response bodies to make the ES logs more useful.  (e.g. a body and, when no parse failure, bodyJson property)?

This would help us do things like ask "how many returned meds have a "system: rxnorm" in their code?

**Comment by erikwiffin** [comment]
Fixed with https://github.com/sync-for-science/reference-research-app/pull/18 and https://github.com/sync-for-science/test-suite/pull/53.
