### ISSUE TITLE
Shared components between Test Suite and Demo App?

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#49]
Or update demo-app to use https://github.com/smart-on-fhir/client-py ?

**Comment by erikwiffin** [comment]
At the moment a shared component doesn't seem to be worthwhile, going to use client-py instead.  https://github.com/sync-for-science/reference-research-app/pull/14 resolves this issue.

**Comment by jmandel** [comment]
Closing now that https://github.com/sync-for-science/reference-research-app/pull/14 is merged.
