### ISSUE TITLE
Filter search parameters to expected list

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#5]
As a project maintainer, I want to limit the queries that can be used against my FHIR API so that I am more confident about the data that I am returning.

Since we’re implementing such a small subset of FHIR, we should be able to block any search queries that contain parameters other than patient, category, and _lastUpdated.

**Comment by jmandel** [comment]
Alternatively we could allow these queries through but simply ignore all parameters other than the ones that we choose to support. Note that some additional fields should still be allowed, including:
- `_count` (a hint about desired page size
- `_format` (when accept  headers are unavailable)... 
- and probably others.

**Comment by erikwiffin** [comment]
The reason I was thinking blocking instead of ignoring was that since this is a sample implementation, it makes more sense to be very explicit about what's we're actually responding to. Also, HAPI complains if it gets parameters it doesn't expect, so this would more or less just be expanding on that scope.

```
Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Patient] with parameters [[notarealparam]]
```

**Comment by jmandel** [comment]
It's a fair point -- and I'm happy to be very explicit on this (we'll just have to tweak the whitelist a bit as we get started to make sure we're not forgetting anything). Certainly it's better from a security perspective to be explicit here :-)

**Comment by jmandel** [comment]
(Though: when it comes to errors on _invalid_ params: we'll be returning an error either way; from the client side, it's not that big a deal whether the error is proxied from HAPI or generated by us on initial inspection.)
