### ISSUE TITLE
"Decline" flow for approval in Dr. Smart's portal

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#56]
... should act gracefully, redirecting back to app so a nice message can be displayed.

**Comment by erikwiffin** [comment]
Does this work https://github.com/sync-for-science/auth-proxy/pull/14/files#diff-7543ca2fa2e82a2aae71352b70a5a29cR8?

**Comment by jmandel** [comment]
The thing to do is redirect to the OAuth redirect_uri with `&error=access_denied`. Details at https://tools.ietf.org/html/rfc6749#section-4.1.2.1
