### ISSUE TITLE
Test revocation workflow 

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#62]
In anticipation of forthcoming vendor support for a relocation workflow, we should build out tests for the following:
1. Complete the usual authorization process
2. demonstrate that we have access to Patient data.
3. Perform the revocation workflow
4. repeat the requests for data and ensure that it fails

**Comment by erikwiffin** [comment]
Should be fixed by https://github.com/sync-for-science/test-suite/pull/57.
