### ISSUE TITLE
Problem with test (or debug logs): Special characters in "state"

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#66]
The Epic server is failing our _Special characters in "state"_ test, but it's unclear why. Two issues here:
#### 1. Limited debug output

Our test suite output includes a nicely-formatted request summary like the following — but no raw request/response details, which makes debugging difficult:

```
Assertion Failed: Returned state parameter does not match sent state.

Sent
----
{'aud': 'https://open-ic.epic.com/Argonaut/api/FHIR/Argonaut/',
 'client_id': 'ad3fe986-cbad-4fcc-a487-3e9ee1ef3a4d',
 'redirect_uri': 'http://tests.dev.syncfor.science:9003/authorized/',
 'response_type': 'code',
 'scope': 'launch/patient patient/*.read offline_access',
 'state': '`%2B~!@#$%^&*()-_=+[{]}\\;:\'",<.>/?'}

Received
--------
{'code': ['QKJBZY/OvAPqo6gK6tT1pn7sCieCGD8clOJ+sL53os5aObXnYmH8Yi2aAHkz/1v2v5O4wByjhuu48im+M5Uos7OPAVFxO0cqITQ+US2CV21j6nfZO9Y6dDTZHuZvNGeK'],
 'state': ['`+~!@']}

```
#### 2. Unclear test suite behavior

The Epic team has indicated they're responding with a payload that _looks right_, and certainly contains more characters that the "Received" state value displayed in the test suite. Possibly the test suite is cutting off the response at the `#` (and possibly correctly). I'm sure we have some issue like "the net end-to-end system is URL decoding n times, while URL encoding (n-1) times" —  but this will be much easier to debug with more details in the test suite output.

**Comment by erikwiffin** [comment]
Based on that output, I think Epic is not urlencoding their state value. You'll notice that it says we're sending them `%2B` instead of `+`, and they're responding with `+`.

Either way, I'll look into improving the debug logs.

**Comment by clark-downum** [comment]
Glad you’ll investigate an improved debug log.

We dug into our full flow after reading Eric's comment.  The initial (redirect) response is properly URL encoded, but the final response appears to be a URL with a non-encoded value for the query string.  

The received state (above) is what I would expect from that given the `%2B` getting encoded to `+` and termination of the query/bringing of the fragment with the `#` in the non-URL encoded state query parameter.

We'll investigate, but I think we're the ones who jumbled up the url encoding/decoding at some point in the flow.  I believe we can close this issue at this time, we’ll reopen should our investigation warrant further discussion.
