### ISSUE TITLE
CVX Code validation broken working

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#69]
Immunizations, I see a warning on Cerner like:

```
And Immunization.vaccineCode is bound to http://hl7.org/fhir/sid/cvx 
```

But in the end-of-test report, `http://hl7.org/fhir/sid/cvx` is listed as "Unrecognized". This seems to make it impossible to pass. The codes from http://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=cvx should be loaded into this value set (or else we shouldn't be assessing this at all).

**Comment by jmandel** [comment]
FYI @daliboz @kpshek

**Comment by kpshek** [comment]
Thanks for the heads up @jmandel. I've opened up an issue on our end to track & fix this.

**Comment by daliboz** [comment]
Sorry, I misunderstood the point/background for this issue. The Immunization in question is "freetext" and not coded in our system. The DAF profile indicates that codeableConcept is required, but usually filling out "text" in this field is acceptable and then, if there is a code, it must be CVX per bindings. The Argonaut profile is less clear - it says "one vaccine code in vaccineCode" which I read to be similar to other concepts in that "text" is acceptable if there isn't a code.

Do we really expect all Immunizations, reported or not, exception or not, to be coded?

http://argonautwiki.hl7.org/index.php?title=Immunizations#Mandatory_Data_Elements
http://hl7.org/fhir/daf/daf-immunization.html

**Comment by jmandel** [comment]
We're just highlighting missing codes with a warning; it's fine if your sample data is not fully coded!

**Comment by daliboz** [comment]
I think this could also happen in production, so I do want to make sure I understand what the intent of the Argonaut IG is. We'll swing back through with this and another issue/question on the group.

**Comment by torresdrew** [comment]
I think what Jenni is highlighting that even production vaccination may be freetext. Our clients have a significant amount leeway in build, and frequently build out proprietary terminologies. They frequently free text items.

**Comment by jmandel** [comment]
Understood! And that's why we're not triggering an error -- just a warning. The fact is that free-text vaccinations are part of the real world; but they're also a place where data quality could be improved, so we highlight them.
