### ISSUE TITLE
DAF Problem validation bug

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#70]
The DAF problem valueset is just a subset of snomed, so when the BF builder tries to read http://hl7.org/fhir/DSTU2/daf/valueset-daf-problem.json it doesn't find anything useful. This means that the validation step always fails.

> And Condition.code is bound to http://hl7.org/fhir/ValueSet/daf-problem

Should this just be bound to SNOMED instead? Or should we try to get just the subset of snomed that is appropriate.

Looks like there is a similar problem with procedures as well:

> One Identification of the procedure in Procedure.code which is bound to:
> - SNOMED CT Value set or
> - CPT-4/HCPC for procedures Value set

Which we have defined as:

> And Procedure.code is bound to http://hl7.org/fhir/ValueSet/procedure-code or http://www.ama-assn.org/go/cpt

(The definition _says_ SNOMED CT, but the link goes to http://hl7.org/fhir/valueset-procedure-code.html where it defines the valueset as a subset of snomed)

**Comment by jmandel** [comment]
Just for pragmatic purposes, I'd suggest overriding the definition http://hl7.org/fhir/DSTU2/daf/valueset-daf-problem.json with "any valid SNOMED CT code" -- unless you have an easy way to construct just the relevant subtrees.

And similarly for procedures, I'd interpret as "any valid SNOMED code".

That will get us to the point, at least, where valid data pass our tests. And most invalid data fail. Does that make sense?
