### ISSUE TITLE
If Conformance omits "Patient", all data tests are skipped

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#73]
Currently Athenahealth's conformance statement lists all resources _except_ patient; and currently all data tests are skipped. Looks like a bug in the test suite logic.

**Comment by ndeen** [comment]
Also, for athenahealth, the test suite is hitting “ https://preview.athenahealth.com/**1/1**/login/oauth.esp?...”

It should be hitting “https://preview.athenahealth.com/**1**/login/oauth.esp?...”

**Comment by jmandel** [comment]
Currently the test suite should be hitting the `authorize` endpoint that athenahealth lists in [its Conformance statement](https://apitest.athenahealth.com/preview1/195900/1/fhir/dstu2/metadata), which looks like:

```
         "security" : {
            "extension" : [
               {
                  "extension" : [
                     {
                        "url" : "authorize",
                        "valueUri" : "https://preview.athenahealth.com/1/1/login/oauth.esp"
                     },
                     {
                        "url" : "token",
                        "valueUri" : "https://preview.athenahealth.com/htservices_external/ecosystem/oauth/ws.esp"
                     }
                  ],
                  "url" : "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris"
               }
            ],
```

Can you update this value in your conformance statement so it looks like what you want?

**Comment by erikwiffin** [comment]
Closing this because these tests being skipped is related to our inability to authorize, not the resources in a conformance statement.
