### ISSUE TITLE
Establish authentication for research-app-api

### ISSUE THREAD

**Issue by erikwiffin** [sync-for-science/tracking#80]
Currently the research-app-api does not come with any authentication or authorization control. We should look into whether or not a firewall is sufficient, or if an API key or Auth header is appropriate.

**Comment by jmandel** [comment]
Thanks for logging this. Overall, I think in _some_ deployment scenarios authentication may be less important, but it's a very simple feature and allows the backend to be used in more flexible ways (without a vpn in place to the caller), and in any case using authentication should be considered part of a "defense in depth" approach.

**Comment by erikwiffin** [comment]
Resolved by the pair of commits https://github.com/sync-for-science/reference-research-app/pull/20 and https://github.com/sync-for-science/research-app-api/pull/3.
