### ISSUE TITLE
Create a locked-down local stack

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#94]
Goal: a docker stack that can run on a locked-down local laptop, including:

 * `api` (not mapped to external network)
 * `tests` (base url: https://test-suite.pilot-prep.syncfor.science)
 * `research-app-api` (not mapped to network)
 * `app` (base url: https://demo-app.pilot-prep.syncfor.science)
 * `nginx`

... this should include an `nginx` instance that mounts SSL certs/keys for the two relevant domains, and a static config file that proxies the two domains to the `tests` and `research-app-api`.

TODO:
- [x] @jmandel get SSL certificates for the two subdomains
- [x] @jmandel create a docker-compose file + nginx container to make this work :-)
- [ ] @erikwiffin document the OAuth client details for both apps, so we can share them with the Pilot vendors

**Comment by jmandel** [comment]
Generating certs via https://github.com/sync-for-science/pilot-prep — this uses DNS-based verification, which allows for letsencrypt certs for domains that point to a non-public IP like `127.0.0.1`.

**Comment by jmandel** [comment]
Ok, I updated https://github.com/sync-for-science/pilot-prep with a docker-compose file and ssl proxy configuration.

Next step: @erikwiffin we should decide on a way to share secrets. Basically all the stuff currently in gitignore. Could be gpg with or ansible vault or whatever. Something you've worked with before that you like?

**Comment by jmandel** [comment]
(Time on an airplane.. I took a first stab at configuring secrets. See https://github.com/sync-for-science/pilot-prep/blob/master/README.md and let me know what you think @erikwiffin)

**Comment by erikwiffin** [comment]
Looks reasonable so far. Obviously I can't get it running without the config files.

I think ansible vault is probably overkill for this setup. It's best when you're deploying something, I don't know that you can use it to just decrypt individual files. I've used https://gpgtools.org/ as well, but I think we'd need to send everyone who wanted to use this suite their own copy of the config files encrypted with *their* public key.

Have you considered encrypted zip files? They could be checked into the git repo, and we'd just have to pass around a password.

Unrelated, getting docker up and running on a mac is a deeply confusing process. Homebrew recommends you run boot2docker, boot2docker claims to be deprecated and recommends docker toolbox, docker toolbox installs docker machine and provides no direction for actually starting the docker engine locally, and the thing that ended up working was installing docker directly from a .dmg.

**Comment by jmandel** [comment]
In the current example I'm actually using `gpg -c` for symmetric encryption (so it has many of the same properties as the encrypted zip idea).

Re: where this runs, I'm fine saying that our only target is Ubuntu (since after all the idea of this stack is just to support a few controlled machines during our pilot). I'm planning to order a pair of identically configured linux laptops for this purpose...

**Comment by erikwiffin** [comment]
Can you send me a `secrets.tgz.gpg` with a password so that I can test this out? Or do the configs we're currently using for the smart stack just work?

It's not actually *hard* to install docker here, just confusing. But yeah, running docker on Ubuntu is a much more straightforward experience.

**Comment by erikwiffin** [comment]
That all worked for me. I'm satisfied going forward with this setup if you are.

**Comment by jmandel** [comment]
Cool! I'd say yes, unless you're inspired to try something else.
