### ISSUE TITLE
Migrate to new Cerner sandbox

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#96]
Following instructions at https://groups.google.com/forum/#!topic/cerner-fhir-developers/CYUZmgOFGls

**Comment by erikwiffin** [comment]
I've migrated our credentials to the new sandbox, but it looks like they've changed how they're handling launch codes, which will break everything. They'll need to start supporting the "Standalone launch sequence" or all their tests will start failing.

**Comment by daliboz** [comment]
@erikwiffin Is this all done/everything working now? We'll be taking down the old sandbox this week.

**Comment by erikwiffin** [comment]
Yep, it looks like everything's been moved over.
