### ISSUE TITLE
When checking coding bindings, check all codings

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#97]
When we say "observation has a LOINC code", this means that *at least one coding* has a valid LOINC code. Currently it looks like we're just inspecting the first.

**Comment by erikwiffin** [comment]
We were actually testing that *all of them* were valid LOINC codes. It just so happened that their first code failed the test, and it stopped there. Now we only require that there be at least one LOINC code, and that it is valid.

**Comment by sudo-something** [comment]
I believe I've found another instance of this happening for the vital signs scenario, step 9 (And Observation.code is bound to http://argonautwiki.hl7.org/ValueSet/argo-vital-signs). In this case, the 2nd code satisfies this requirement. Will this fix apply to this scenario as well or should I create a new issue to track?

Side note - that url above is not resolvable. Searching, I found this http://www.fhir.org/guides/argonaut/r2/ValueSet-observation-ccdavitalsignresult.html and http://argonautwiki.hl7.org/index.php?title=Argonaut_Vital_Signs. Not sure if it should be updated but wanted to point out, just in case.

**Comment by erikwiffin** [comment]
This fix should fix that scenario too. It filters for only codes that match
the URL, asserts that there's something left, and then checks that they're
all valid.

I don't think that the url needs to resolve, but I think it's still wrong.
The URL I have defined in
https://github.com/sync-for-science/test-suite/blob/master/data/fhir/argo-vital-signs.json
and the one defined on
http://argonautwiki.hl7.org/index.php?title=Argonaut_Vital_Signs is
http://hl7.org/fhir/us/argonaut/ValueSet/argo-vital-signs, so I'll update
it to that.

**Comment by erikwiffin** [comment]
Based on the URL, I wonder if
http://argonautwiki.hl7.org/index.php?title=Argonaut_Vital_Signs used to
redirect/forward to http://argonautwiki.hl7.org/ValueSet/argo-vital-signs?

**Comment by sudo-something** [comment]
Perfect - thanks for the quick update. One other question; do you happen to know when the next release will be cut and deployed?
